# Generated by Django 5.0.6 on 2025-03-03 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebook',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
