# Generated by Django 5.0.6 on 2025-04-05 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebook', '0004_chapter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ebook',
            name='content',
        ),
    ]
