# Generated by Django 5.0.6 on 2025-04-05 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebook', '0005_remove_ebook_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='order',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
